### ISSUE TITLE
Surface Pro 3 Device - Viewing Problem - Overlapping Text. John Holland

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#105]
Chris O'Shannessy from John Holland Group sent through this view of Cases:

- [ ]  Is Screenshot of the Cases page: No Plant Identifier number. I assume this is due to the fact that Metro are ditching the VIC numbers. This is a problem at the moment because when we go into Cases, there are 3 excavators and we can't identify which one is which with the little information. 
- [ ] When you go into a particular Case for a piece of plant - for example VIC 5402013 all the Text is on top of each other when he views... See screenshot attached.
![particular case](https://cloud.githubusercontent.com/assets/25288888/24233701/f19750f0-0fe7-11e7-9770-df3d058473c7.jpg)

![plant identifier missing](https://cloud.githubusercontent.com/assets/25288888/24233625/8401fcb6-0fe7-11e7-8518-53cc27c84a7a.jpg)

- [x]  See attached a document which gives you the Specs of his Device and the Windows operating system. 
![surface pro 3 specs](https://cloud.githubusercontent.com/assets/25288888/24233728/1b7f95bc-0fe8-11e7-81b1-0f4478b034e1.jpg)

Thank you.....

**Comment by jpike88** [comment]
Closing and reopening seperate issues for the problems
