### ISSUE TITLE
View Case is borked in IE(10+)

### ISSUE THREAD

**Issue by jpike88** [streaka/plantguard-issues#107]
@LachiePenn

**Comment by jpike88** [comment]
![f19750f0-0fe7-11e7-9770-df3d058473c7](https://cloud.githubusercontent.com/assets/9585787/24234141/81f6c53c-0fe2-11e7-87c0-f897a3a34130.jpg)

**Comment by LachiePenn** [comment]
See screenshot attached of Chris's view: NOTE: I am finding out what IE version he is using. 

This is his exact comment:
"Still overlaid in Internet Explorer as attached.  I also checked under Google Chrome (not supported by our IT dept) it looks good."

![ie view cases](https://cloud.githubusercontent.com/assets/25288888/24235505/b4278726-0ff1-11e7-8d8e-60d38f8115c6.png)
