### ISSUE TITLE
Pete's Contracting Pty Ltd - Import Plant into PG from Google Sheet

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#108]
Pete's Contracting is in PlantGUARD as a Supplier.
Can you please import the 1 piece of plant and let me know when done so I can notify them.

https://docs.google.com/spreadsheets/d/17OeJWl9g2xdR8C32ut1e3J-5s4wb2uA1Je7WSTpvvgE/edit?usp=sharing

Thank you.

**Comment by jpike88** [comment]
completed

**Comment by LachiePenn** [comment]
There is no Plant showing in this account in PlantGUARD..... should be 1 piece of plant to be verified.

**Comment by jpike88** [comment]
try now, good to go. was an issue with the importer
