### ISSUE TITLE
John Holland Group - Plant Data Changes and Issues Raised

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#112]
Can we please address the changes for these plant in John Holland Group account. (MTM Supplier)

- [x] VIC 8212015 - Please remove Restriction Code M62 for this plant. This is a confirmation from my discussions with Marta. It is wrongly included. 

- [x] Plant hash: a1da98a1-a11f-4e5a-9167-2c09239d0a94 
Plant identifier: VIC 8292015 
ACTION: Vehicle is identified as a tamper in PG - it is actually a Compactor manufactured by a company named "Tamper"

- [x] VIC 8282015 I realised after verifying that it is listed as a ‘Plasser’ Tamper when it is in fact a ‘Tamper’ brand Compactor
ACTION/CHANGE: it is actually a Compactor manufactured by a company named "Tamper"

- [x] Plant hash: 5161c891-af1e-4427-bcbc-a6c6efa4ad0a 
Plant identifier: VIC 5052013 
ACTION: Excavator JH asset number 323059 decommissioned. Can be removed from PlantGUARD

- [x] Plant hash: 9473fbc0-d65e-4669-acdf-f0653751d1ee 
Plant identifier: VIC 5072013 
ACTION: Excavator JH asset 323061 has been disposed of and can be removed from PlantGUARD.

- [x] Plant hash: 143bf64b-4fd0-484c-a6a2-ee46f908492a 
Plant identifier: VIC 8352016 
ACTION: Vehicle make is Mercedes with Techniplan (incorrectly spelt in plant details) modifications.

**Comment by jpike88** [comment]
Sorry about delay! Done
