### ISSUE TITLE
John Holland Group - One more Change of plant in PG

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#113]
Please see these 2 extra change for Plant in John Holland account. Came through this morning.

- [x] Plant hash: 5161c891-af1e-4427-bcbc-a6c6efa4ad0a 
Plant identifier: VIC 5052013 
ACTION: VIC5052013 - Excavator - Komatsu PC138US-8 serial no.23599, JH asset 323059 has been decommissioned. PLEASE REMOVE FROM PlantGUARD

- [x] Plant Identifier: 311M43 Rego: XZW-558 - See attached screen shot of an Rail Maintenance Services (RMS) piece of plant that is showing under the Assessment section of the Plant menu in John Holland Group.

![screen shot 2017-03-31 at 1 40 06 pm](https://cloud.githubusercontent.com/assets/25288888/24534233/5d091d7e-1618-11e7-97d4-77bd986ea1ae.png)

**Comment by alexkingma1** [comment]
First point completed.

For the second issue, the reason RMS's plant is showing up to JHG is because they are the assigned assessor for the MTM RRV assessment that the plant is linked to.

**Comment by LachiePenn** [comment]
On the second point: Oh!
- So John Holland Group is not currently a recognised Assessor for Metro .... so can we remove them as an Assessor for now?
- So does this raise an Issue if a Supplier is also an Assessor. (Lets use JHG as a example) The guy Chris who looks after JHG plant that they supply to MTM, has nothing to do with Plant that JHG may assess for other businesses. To see plant to be assessed by another department confuses Chris.

**Comment by jpike88** [comment]
- Done
- We can add a notice when viewing that plant that it's visible because they're designated as assessor for it, for now. Worth bouncing that off @markstreaka. Closing this as it's its own requirement
