### ISSUE TITLE
Expiry Dates Confirmation & Fix if needed.

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#118]
Request from Matt Sekulitch: (this is Metro's own Plant)

- [x] 1CD-7AO : Can you check the subject bit of kit and set the expiry date to 19 Dec 2017.
- [ ] ZHV-722 : What is the current Expiry Date for Assessed Vehicle that in in PG?
- [ ] YLP-687 : What is the current Expiry Date for Assessed Vehicle that in in PG?

Thank you......

**Comment by jpike88** [comment]
1CD-7AO: done
ZHV-722: 31st August 2015
YLP-687: 28th April 2017
