### ISSUE TITLE
Plant History

### ISSUE THREAD

**Issue by markstreaka** [streaka/plantguard-issues#123]
I have completed a pre-start checklist for johnsupplier plant 30M1 and when I go to plant view I cannot see in history a record of that checklist having been performed

**Comment by jpike88** [comment]
We've temporarily stopped the form processing queue for bug fixes, this should appear shortly

**Comment by alexkingma1** [comment]
Log events for the following categories of plant activity:
- [ ] application
- [ ]  assessment
- [ ] checklist
- [ ] task
- [x] case
- [ ] service
- [ ] plant-edit
- [ ] flag
