### ISSUE TITLE
Add Rego, Red to Green Flag, Remove from Cases

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#125]
- [x] Gillies Earthmoving - VIC 9322016
Can you add this Road Registration, was previously unregistered and also update the Assessment Expiry Date..
ACTION: add this Registration number for this plant: 1GW3PW
ACTION: Assessment Expiry Date needs to be changed to 11-02-2019
[1974_001.pdf](https://github.com/streaka/plantguard-issues/files/908594/1974_001.pdf)

- [x] Rail Maintenance Service - VIC 2852013 (PG: 311M3)
ACTION: Update Assessment Expiry Date - Take from Red Flag to Green Flag - New Expiry date will be 14-02-2019
[2852013.pdf](https://github.com/streaka/plantguard-issues/files/908595/2852013.pdf)

- [x] Eastern Tree Services - VIC 2732017 (PG: 473M1)
ACTION: Take from Red to Green Flag - Update Assessment Expiry date to 31-03-2019
[2732017.pdf](https://github.com/streaka/plantguard-issues/files/908603/2732017.pdf)

- [x] McConnell Dowell - VIC 7022017 (PG: 299M3)
ACTION: Take from Red to Green Flag - Update Assessment Expiry date to 28-02-2018
[VIC7022017.pdf](https://github.com/streaka/plantguard-issues/files/908609/VIC7022017.pdf)

- [x] John Holland Group - Login as JHG and go to Cases. VIC 5052013 & VIC 5072013 both Excavators have to be removed from Cases. They have been decommissioned. I wasn't sure how to Close the Cases, as when logged in as MTM I can't see them.

**Comment by jpike88** [comment]
@LachiePenn Side note: Red flag can be purely due to an overdue assessment. Just moving these assessment dates forward will make it green automatically. Force flag isn't occurring on any plant yet

Here's a diagram worth a glance:

**Comment by jpike88** [comment]
Sorry we already chatted about that... comment was half typed
