### ISSUE TITLE
P&C Excavations Only (Rail Lines Australia)

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#127]
Should be just these 2 for the moment: 

- [x] VIC 6292014 - Red Flag to Green Flag - Has been assessed. (Currently in Verification in  PG)
ACTION: Expiry Date set to 15-02-2018
[Truck Tipper VIC6292014.pdf](https://github.com/streaka/plantguard-issues/files/908704/Truck.Tipper.VIC6292014.pdf)

- [x] VIC 6272014 - Red Flag to Green Flag - Has been assessed. Rego: WQL-680
ACTION: Move to Green Flag Status - Set Expiry Date to: 16-03-2018

**Comment by LachiePenn** [comment]
Josh... you have got these wrong in their expiry dates.... you need to swap them around.

**Comment by jpike88** [comment]
Done
