### ISSUE TITLE
[ViewTask/ViewCase] comment field is not cleared after comment submit

### ISSUE THREAD

**Issue by jpike88** [streaka/plantguard-issues#132]

**Comment by alexkingma1** [comment]
Case/Task closing also ignores any pending comment. Either conversations should not be closeable while a comment is pending, or the comment should be submitted prior to the close() call (and the button label should indicate this functionality).

**Comment by jpike88** [comment]
https://github.com/angular-ui/ui-select/issues/18

Looks like a weird behaviour with scoping... fixed by whacking a parent object in there and attachment ng-model to a property of it. No comment
