### ISSUE TITLE
Input of Plant

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#162]
- [x] Hardface Technologies - (MTM Supplier) Can you input this 1 piece of plant into their account:
https://docs.google.com/spreadsheets/d/1RtGo-G5AF7LYv_W_YlUKRoKx2ASdxeVuCqxt0s0da7I/edit?usp=sharing

- [x] Searles Transport Pty Ltd - (Aurizon Supplier)- can you import the 3 plant into there account so they can verify. One is still missing a Manufacture - am informed she is chasing this up. 
https://docs.google.com/spreadsheets/d/1cWOVPym6QtTl1kjLi88hmqolw8Q9t2nZBHAgrD6I1rk/edit?usp=sharing

- [x] MTM Import Spreadsheet - go to the first Tab down bottom > PLANT TO IMPORT > see Rows 2,3,4 > can you please import only those top 3 rows so those businesses can verify the Plant. 
https://docs.google.com/spreadsheets/d/1PeNQztCz2zzFanjeVgkkWuRglQ3KkIq8_I447XQHck0/edit?usp=sharing

**Comment by jpike88** [comment]
Can you check the MTM spreadsheet and confirm those three are the plant you're referring to?

**Comment by LachiePenn** [comment]
Josh, have had a look at the MTM spreadsheet. I have now deleted 2 of the 3 from the Import Tab as they are in PG. The only one left of the 3 is the VIC 2322017 which is for P&C Excavations.

This is nothing to do with the Importing of plant for Hardface and Searles Transport which are the two other points in this Issue.....

**Comment by LachiePenn** [comment]
Josh.... have just seen that the VIC 2322017 has been imported into PlantGUARD for P&C Excavations, thus confirming that they were the 3 plant that I was referring to.... Very Good!!!!

**Comment by jpike88** [comment]
@LachiePenn Searles still missing that YOM, assign an intercom convo to you
