### ISSUE TITLE
Tenex Rail & Excavations Pty Ltd

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#165]
Josh a couple of things we need to do for Matthew at Tenex:

- [x] Plant 318M1 - Excavator
ACTION: Please change the date of manufacture to 2012 (its currently 2008 - wrong)
Note: Matt did provide documentation to get this out of Red Flag, I await Metro's confirmation and new Label so we can change the Assessment date.

- [x] ACTION: New Plant to Import into PG for Tenex. Please see this in the MTM Import Spreadsheet:
https://docs.google.com/spreadsheets/d/1PeNQztCz2zzFanjeVgkkWuRglQ3KkIq8_I447XQHck0/edit?usp=sharing
See attached the Current Label - how do we know what the Restriction codes are supposed to be???
[Tenex_VIC6402013.pdf](https://github.com/streaka/plantguard-issues/files/985081/Tenex_VIC6402013.pdf)

**Comment by jpike88** [comment]
The restriction codes are on the label you attached. all good, done
