### ISSUE TITLE
Change Restriction Codes and cross-check Expiry Dates and VIN

### ISSUE THREAD

**Issue by markstreaka** [streaka/plantguard-issues#186]
[John Hollands Vehicles.xlsx](https://github.com/streaka/plantguard-issues/files/1002752/John.Hollands.Vehicles.xlsx)

As per the attached spreadsheet which is the most up-to-date and accurate data for these John Holland plant, please:
1. Update restriction codes
2. Cross check expiry and change where there is a conflict
3. Cross check VIN and change where there is a conflict
4. Make note of the plant that required change of Expiry and/or change of VIN as new stickers will need to be ordered for these.
5. Reset Download certificate to "0" so that they can download the certificate again
6. Check that Download Certificate works as there were some problems with this yesterday when reset to "0"

**Comment by alexkingma1** [comment]
A number of the JHG plant on the system are not mentioned in this spreadsheet. Should I ignore these?

**Comment by alexkingma1** [comment]
[John.Hollands.Vehicles.xlsx](https://github.com/streaka/plantguard-issues/files/1003100/John.Hollands.Vehicles.xlsx)

I have added a column to the above spreadsheet regarding which plant need their certificates re-downloaded.
Four plant were in our system, but not in the spreadsheet; I ignored these. All mentioned plant are now up to date in plantguard.
