### ISSUE TITLE
Johns Plumbing Service - Import Plant - Aurizon Supplier

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#195]
- [ ] ACTION: Please import plant from this Spreadsheet for Johns Plumbing:
https://docs.google.com/spreadsheets/d/1SPRmwaUZhlDhYlZlqQ1BYYaogT9OB0m5hLjeCgoKo58/edit?usp=sharing

Note: the above spreadsheet link is not the Google sheet link via the sub-menu.
See attachment of Sub-menu: 
![jp s plumbing google sheet](https://cloud.githubusercontent.com/assets/25288888/26272928/c919c952-3d67-11e7-9fc0-69210305319d.jpg)

**Comment by jpike88** [comment]
completed, they'll need to be moved into verification by yourself
