### ISSUE TITLE
Aurizon Plant Application Functionality

### ISSUE THREAD

**Issue by markstreaka** [streaka/plantguard-issues#214]
_Please fill out this template thoroughly, for the sake of our sanity._

## **What did you expect to happen?**

See video http://streaka.testing.videos.s3.amazonaws.com/screencast_2017-05-24_10-28-45.mp4
## **What actually happened?**

See video http://streaka.testing.videos.s3.amazonaws.com/screencast_2017-05-24_10-28-45.mp4
## **Steps to Reproduce Issue**
See video http://streaka.testing.videos.s3.amazonaws.com/screencast_2017-05-24_10-28-45.mp4
(preferably video in Chrome with inspector open with console visible)

## **What platform was this on?** 
Chrome
(Browser/iOS/Android)

**Comment by jpike88** [comment]
@LachiePenn
