### ISSUE TITLE
Independent Services

### ISSUE THREAD

**Issue by jpike88** [streaka/plantguard-issues#216]

**Comment by alexkingma1** [comment]
- [x] allow manual logging of services (using standard service form)
- [x] allow manual specification of once-off service due parameters
- [ ] show all pending services on view plant page
- [ ] [OPTIONAL] add latest odometre, hour, fuel readings to a (existing?) plant card
- [ ] ensure services are being marked as overdue server-side on submission of various checklist/service forms
