### ISSUE TITLE
Service functionality

### ISSUE THREAD

**Issue by alexkingma1** [streaka/plantguard-issues#22]
- [x] Add to serviceService a configure service function that fires up a dialog with distance and/or hours and/or date of upcoming service (needs to be in the future).
- [x] This can be opened via Schedule Service button

- [x] 'Schedule service' needs to say 'Reschedule service' and not duplicate the row
- [x] Start building out heartbeat.js to periodically check elapsed service schedules. The method that 'triggers' an elapsed services needs to be made easily available from other parts of the webapp as I will call that same method when checklists get submitted
- [x] On elapsed schedule: Email all supplier users with notifications turned on (use a notifications.js wrapper as it would have a push notification equivalent, maybe with a shorter description of the 'event'.)

- [x] Ability to assign an existing checklist to a particular rule group.

**Comment by jpike88** [comment]
- [ ] Add to serviceService a configure service function that fires up a dialog with distance and/or hours and/or date of upcoming service (needs to be in the future).
- [ ] This can be opened via Schedule Service button

**Comment by jpike88** [comment]
- [ ] 'Schedule service' needs to say 'Reschedule service' and not duplicate the row
- [ ] Start building out heartbeat.js to periodically check elapsed service schedules
- [ ] On elapsed schedule: Email all supplier users with notifications turned on (use a notifications.js wrapper as it would have a push notification equivalent, maybe with a shorter description of the 'event'.)

**Comment by jpike88** [comment]
@markstreaka

**Comment by jpike88** [comment]
closed due to re-calibrated specifications

**Comment by jpike88** [comment]
service regime page

+ button on all pages remove

when no service regime, have the row display (in italics):

“Service regimes provide an easy way of configuring when services may be needed by your plant.

Typically, service regimes apply to particular types of plant (e.g. all of your excavators), or may follow a particular OEM manual recommendation.

Click here to create your first service regime.
“

In create dialog, have in italics above the field

“Create a label for your service regime (e.g. Excavators)”

On creating one, they then are redirected to that new service regime’s page.

“A service consists of multiple rules. When any of these rules are met, the plant will be flagged as requiring that service.

You may also create service checklists that can be assigned to a service. This will allow you to fill out the checklist easily at the time of service.

Add services to this service regime by clicking here.”

In create dialog, have in italics above the fields

“Fill out a name for your service ( e.g ‘500 hours’, ‘Service 7-64192’ ), and attach a service checklist if you have one available.”

when created,

**Comment by jpike88** [comment]
- [ ] perform tweaks on misc branch and watch for mark's test commit (just discard it)
- [ ] rename 'information' to 'tooltip'
- [ ] spanning between heading and text in info bar, make it smaller
- [ ] background colour of underlying div is #f5f5f5 (this is a universal thing, should occur everywhere (hint: style md-content)
- [ ] rename 'service' to 'service schedules'
- [ ] On page that shows service schedules for a given regime, this sits in the blue bar: Regime - [regime_name] - Service Schedules
