### ISSUE TITLE
Duplicate checklist for business is duplicating checklist for super admin NOT the intended business

### ISSUE THREAD

**Issue by markstreaka** [streaka/plantguard-issues#237]
_Please fill out this template thoroughly, for the sake of our sanity._

## **What did you expect to happen?**

http://streaka.testing.videos.s3.amazonaws.com/screencast_2017-05-30_12-30-21.mp4
## **What actually happened?**

http://streaka.testing.videos.s3.amazonaws.com/screencast_2017-05-30_12-30-21.mp4
## **Steps to Reproduce Issue**
http://streaka.testing.videos.s3.amazonaws.com/screencast_2017-05-30_12-30-21.mp4
(preferably video in Chrome with inspector open with console visible)

## **What platform was this on?** 

(Browser/iOS/Android)

**Comment by markstreaka** [comment]
@jpike88 and @alexkingma1 Did this get pushed to production? It is still not working for me so I think there may be some problems with the new staging server that has been set up.

**Comment by alexkingma1** [comment]
@markstreaka I've pushed through the changes and just tested the feature on production now. Checklists you duplicate should now appear for the correct business. Feel free to delete all the ones that were incorrectly copied to the admin account. Doing this will not affect the checklists that appear for other businesses.

Once Josh and I get a bit of familiarity with this new system under our belts, this develop-staging-production flow should become smoother.
