### ISSUE TITLE
As a client I want checklists that suppliers must perform and that come back to me for approval/acknowledgement so that remotely I can manage the safety activities of suppliers out on site.

### ISSUE THREAD

**Issue by markstreaka** [streaka/plantguard-issues#243]
SRD 85 and Height Limiter Checklists are the first checklists that require this functionality. So that:
 - the SRD and Height Limiter checklists automatically appear for all Aurizon suppliers (and ultimately clients should be able to make checklists for distribution to suppliers)
- when suppliers submit these checklists relevant Aurizon users are notified 
- Aurizon staff must Accept or Reject these checklists

Perhaps it is best to use the applications approval process for this as it functions in a similar way.

**Comment by jpike88** [comment]
- [ ] New type of checklist: Client Checklist. Has client group visibility, can only be administrated by clients.
- [ ] Whoever fills it out creates a task for the client regardless of whether needs action columns are filled or not
- [ ] Task does not notify anyone
- [ ] Existing tasks need to be branded with a subtype
- [ ] Task view needs a new view for new types of tasks

**Comment by jpike88** [comment]
Just a modified review step. Creates a task for now.
