### ISSUE TITLE
As a user I want to be able to log a service using one of the service forms

### ISSUE THREAD

**Issue by markstreaka** [streaka/plantguard-issues#257]
See video: http://streaka.testing.videos.s3.amazonaws.com/screencast_2017-06-06_12-17-06.mp4

**Comment by markstreaka** [comment]
Looks good. Did you want me to check something particular with this?

**Comment by alexkingma1** [comment]
Don't think so, as long as nothing is glaringly wrong. Once Josh does another wave of syncing with production, we can move this to Done.
