### ISSUE TITLE
Multiple file upload support on View Plant page

### ISSUE THREAD

**Issue by jpike88** [streaka/plantguard-issues#26]
- [ ] Ensure interface looks like this (can be achieved entirely via CSS):

![drag-drop-upload-1](https://cloud.githubusercontent.com/assets/9585787/22357695/926b6342-e485-11e6-8a0a-540743a93590.gif)

- [x] Clients can do it

**Comment by alexkingma1** [comment]
drag and drop functionality cancelled for now, but multiple file upload is supported. In future, we should look into a dialog interface that opens to allow the complex manipulation of files (one of the features of which will be a div to drag files into from the OS explorer).

**Comment by jpike88** [comment]
good enough for now
