### ISSUE TITLE
Checklists V Services - User Confusion - Needs Discussion ASAP

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#271]
After discussion with Trish - John's Plumbing.
Confusion around what Checklists should appear under the menu heading Checklists and what should appear under Services (and not call them Checklists - even though to us they are a Service Checklist) 

This is on the left hand Menu Bar where we have Checklists and Services but also in the Sub-Menu of the Plant row where execute options (see below):
![screen shot 2017-06-15 at 2 27 52 pm](https://user-images.githubusercontent.com/25288888/27165401-ff3284ec-51d6-11e7-967e-b8d4c163dbce.png)

She was completely confused with Log Service (being Manual) and then going into say Begin Checklist to find say a 250 Hour Service, why not have all service types just under Services. 

I'm not going to try and explain by typing, this is a conversation/discussion first. It was good and very productive with Trish

It does seem that a Service is a long term action and a Checklist should be a Pre-Start, daily or something that may be required the necessary etc etc... 
This is good, lets organise a chat time that suits all......

**Comment by jpike88** [comment]
My understanding is that there were service checklists showing where they shouldn't, mainly causing confusion here. still need a UI chat though at some point
