### ISSUE TITLE
RMS Bug

### ISSUE THREAD

**Issue by jpike88** [streaka/plantguard-issues#283]

**Comment by LachiePenn** [comment]
RMS Plant in question by Mark Schembri:

- [ ] 311M5 (Vic 9262016) - Case is closed, still orange flagged and appears in Assessment Tab

- [ ] 311M39 (VIC 2682013) - Should be Closed but still appears in Open Case - It has Green Flag the you view plant (However, I don't see in the Case conversation or the Activity Log of the plant that Metro has actually Closed the Case. ???)

- [ ] 311M9 (VIC 3002014) - Mark S says "Should be Closed but still in Open Case" - Mark s has asked the question of Adam as to where things are in the Case conversation - looks like Metro needs to close conversation. (Note: all Green Flags when you go into Plant View)
- [ ] 311M37 (VIC 4762014) - Same as above
- [ ] 311M59 (VIC 4792014) - Same as above

**Comment by jpike88** [comment]
@LachiePenn 

All sorted except for 311M9.

Check out the case:
https://plantguard.tech/#!/app/case/801d9a39-a9c4-440b-8dd1-1325efa5acb5

Tom Barker needs to submit another assessment with the updated brake test results built into it. Attaching them to a case right isn't sufficient, as the assessment needs to be 100% filled in for restriction codes etc to generate properly.
