### ISSUE TITLE
BUG - PlantGUARD > Intercom - User Creation in PG not creating in Intercom

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#290]
- [x] What did you expect to happen?
When I create a New User in a Supplier Account in PlantGUARD, this needs to automatically create a User in Intercom for that business. This is so we can communicate with them.

- [x] What actually happened?
Currently when I Add New User in a supplier account in PG, this does not automatically create that user in Intercom.

- [x] Steps to Reproduce Issue: go in and Add a User

Browsers: Chrome & Safari

**Comment by jpike88** [comment]
Fixed... I think. seemed to only occur with Boom, tweaked some code, let see how it goes
