### ISSUE TITLE
Plant Add Button Occluding buttons (regression)

### ISSUE THREAD

**Issue by jpike88** [streaka/plantguard-issues#298]
![screen shot 2017-06-21 at 7 08 27 pm](https://user-images.githubusercontent.com/9585787/27383448-3b515218-56b5-11e7-93db-bc13d2972b52.png)

**Comment by jpike88** [comment]
any ideas?

**Comment by alexkingma1** [comment]
Maybe move it into the mode/tab bar. Since the button doesn't show on mobile, there should be plenty of space if we flex it to the far right or something. It would become just a regular button, in that case. A FAB doesn't really work on a page with consistent, dense content like a table.

**Comment by alexkingma1** [comment]
similar to how the icon-buttons on the account page work, except in the mode bar instead of the corner of a card.
