### ISSUE TITLE
Rail Maintenance - Case Closed still in Red Flag

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#304]
Rail Maintenance Services - Being questioned by Mark Schrembi (in Intercom) why still in Red Flag status after Case been closed. Can we get into Green Flag?
Plant ID:   311M69 (VIC 2412013) - got to Red Flag Tab

- Says in the Case history that this Case was closed: https://plantguard.tech/#!/app/case/1b4e31a6-18a5-4f30-aed6-9563adeb3dc1 .HOWEVER it is currently in Red Flag status under Assessment Tab. Not sure why?

- Interestingly in the Activity Log of that plant, when Case was closed, says Assessor Nominated and Assessment reviewed (accepted). Is this odd??

![unusual case closed](https://user-images.githubusercontent.com/25288888/27504881-2ff5b24c-58d6-11e7-81c8-833e8aa52fce.png)

**Comment by jpike88** [comment]
Assessments are re chosen on resolving a forced flag case, that's normal. Not sure why the flag didn't resolve to green though I'll check it out

**Comment by LachiePenn** [comment]
@jpike88 Can you look at this one first thing. Have Mark Schembri from RMS on my case. 
Thank you.
