### ISSUE TITLE
Demenna Cranes (Metro) - Updating Plant Details

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#305]
Demenna Cranes - please see following for plant. See my video first: http://streaka.testing.videos.s3.amazonaws.com/screencast_2017-06-24_13-00-06.mp4

- [ ] Plant ID: 278M3 (VIC 8212013) No Restriction Codes in the Plant View for this plant. It is only showing in My Plant tab and not on Green Flag Tab - See video above.
[278M3_Demenna-ZNT-108.pdf](https://github.com/streaka/plantguard-issues/files/1099393/278M3_Demenna-ZNT-108.pdf)

- [ ] Plant ID: 278M1 (VIC 811 2013) - getting a photo sent for this.

**Comment by jpike88** [comment]
@LachiePenn 278M3 is not in MTM because it wasn't submitted as an application, they need to do that

278M1 has no photo, closing issue
