### ISSUE TITLE
Begin Checklist - no checklist to select bug

### ISSUE THREAD

**Issue by markstreaka** [streaka/plantguard-issues#43]
For plant that has no checklist assigned - "Begin Checklist" >> Which checklist would you like to open >> selector is empty even though there has be 2 checklist made for that supplier (Schwarz)

**Comment by jpike88** [comment]
If no checklist have been assigned yet, then all checklists are now available by default.

**Comment by jpike88** [comment]
Actually no. Sorry assign checklist kicks in instead.

**Comment by jpike88** [comment]
Wait, I'll have it just show them all. Probably worth a bit of thought to make a decision (it's a minor tweak to make)
