### ISSUE TITLE
Checklists - section title should be at top of section - below blue and above section description

### ISSUE THREAD

**Issue by markstreaka** [streaka/plantguard-issues#45]

**Comment by jpike88** [comment]
![screen shot 2017-02-13 at 10 40 08 pm](https://cloud.githubusercontent.com/assets/9585787/22883751/63571202-f23d-11e6-87c8-2e6e2e627731.png)

I just did that and now it looks like the attached picture... what should I do?

**Comment by jpike88** [comment]
@markstreaka
