### ISSUE TITLE
Red Flag to Green flag plant fixes

### ISSUE THREAD

**Issue by markstreaka** [streaka/plantguard-issues#73]
expiryEpoch changed but flag status still red:

- [x] LinMag Milling Machine VIC4572015 - see case for this plant
- [x] Truck VIC8112013 - registration expired is reason for case

expiryEpoch changed but plant not verified yet:
- [x] Truck Tipper VIC6292014
- [x] Truck Tipper VIC6282014

Can see in PG but cannot see in plant table:
- [x] Excavator VIC7722013, 
- [x] Excavator VIC7732013,
- [x] Excavator VIC7802013, 
- [x] Truck VIC7882015, 

Not in PG and not in plant table:
- [x] Truck VIC8212013

**Comment by LachiePenn** [comment]
[Excavator VIC7722013.pdf](https://github.com/streaka/plantguard-issues/files/829783/Excavator.VIC7722013.pdf)
[Excavator VIC7732013.pdf](https://github.com/streaka/plantguard-issues/files/829785/Excavator.VIC7732013.pdf)
[Excavator VIC7802013.pdf](https://github.com/streaka/plantguard-issues/files/829786/Excavator.VIC7802013.pdf)
[Truck VIC7882015.pdf](https://github.com/streaka/plantguard-issues/files/829784/Truck.VIC7882015.pdf)

**Comment by jpike88** [comment]
All plant expiration dates have been to 16 Feb 2018 (unix epoch 1518703200)
