### ISSUE TITLE
Goodies Excavations - 2 New Plant to input.

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#80]
- [ ] Line 22 & 23 of Google Doc. 
- [ ] Need to put back into Verification. 

https://docs.google.com/spreadsheets/d/1tHL5erjYBPVPoQiRiXYX7MerXzPJb4DGAKj8XeAywWs/edit?usp=sharing

**Comment by jpike88** [comment]
Still no validation in sight? I'm removing the 'Active' tab to clear out Waffle, you can just comment on this again and I'll wake it up when you're good

**Comment by LachiePenn** [comment]
@jpike88 Can we at the least import the Plant Line 22: Excavator Volvo: 14048C
the other I am still waiting on Height Limiter Info

**Comment by jpike88** [comment]
done

**Comment by LachiePenn** [comment]
@jpike88 I just heard back from Goodies and they are holding off on the other plant for the moment. So leave that one in their court for now. Cheers
