### ISSUE TITLE
Move Red Flag Plant to Green Flag

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#88]
Montgomery (MTM). Matt Sekulitch has provided more Interim Labels for plant that has been assessed. Need to move from Red Flag to Green.

- [x] VIC 7842013 (Note: this is the correct VIC #, its wrong on the Label, I have informed Matt)
- [x] VIC 7852013
- [x] VIC 7862013

**Comment by LachiePenn** [comment]
[VIC8742013.pdf](https://github.com/streaka/plantguard-issues/files/842831/VIC8742013.pdf)
[VIC7852013.pdf](https://github.com/streaka/plantguard-issues/files/842833/VIC7852013.pdf)
[VIC8742013.pdf](https://github.com/streaka/plantguard-issues/files/842834/VIC8742013.pdf)

**Comment by LachiePenn** [comment]
@jpike88 There is no change in these in PlantGUARD.... They should be active green now??

**Comment by jpike88** [comment]
@LachiePenn try now
