### ISSUE TITLE
Change Descriptions elements of Plant for Suppliers

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#89]
Have had calls from 2 of these Suppliers today to update. Were in intercom from a week ago. Cheers

- [x] GTE Welding (MTM Supplier)
Plant hash: cc43eb5b-e8ce-4b15-8a2b-7968e5a45fb4 
Plant identifier: VIC 9302015 
Comment: Not a Welding Truck its actually a Welding Ute. Please change description to Welding Ute

- [x] CH Weed Contractors (Aurizon Supplier)
Plant hash: 17e704ed-8df0-4932-bc0f-6dc750a955db 
Plant identifier: 6TWSTP3ECA1008463 
Comment: I have entered the wrong colour. Please change colour of vehicle to White (Not Cat Yellow)

- [x] Safe Dig (Aurizon Supplier)
Just writing to advise that we have now sold the DAF vac truck registration 652SAF, if you could please remove this truck from the PlantGUARD system.

- [x] Rayment Excavations (Aurizon Supplier)
Plant hash: 83383bcc-627a-460c-947c-c3af37b51eb7 
Plant identifier: 7TSUN 
Comment: Height limit approval number 226 needs to be added

**Comment by alexkingma1** [comment]
I've gone through and made each of the changes, @LachiePenn.
