### ISSUE TITLE
Plant attributes exist with value of '<- please select ->' or some variation, from failed GoogleSheets import

### ISSUE THREAD

**Issue by alexkingma1** [streaka/plantguard-issues#90]

**Comment by alexkingma1** [comment]
i think plant with hash '83383bcc-627a-460c-947c-c3af37b51eb7' was an example.

**Comment by jpike88** [comment]
@LachiePenn these two plant hashes have this issue and need clarification:

83383bcc-627a-460c-947c-c3af37b51eb7
f734538c-0f29-4814-8a8e-71baaeeab2cc

**Comment by LachiePenn** [comment]
Please see clarification in the spreadsheet.

https://docs.google.com/spreadsheets/d/1R66ZN86rjKMcBHCxq0yAE3GwC_Dsp_ZKokN2BoxKb4Q/edit?usp=sharing

Thank you

**Comment by jpike88** [comment]
Updated
