### ISSUE TITLE
Upgrade Plant Status in PG - Red Flag to Green Flag

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#97]
Updates sent by MTM to update across Suppliers. Interim Labels have been provided to the Suppliers by MTM:

McConnell Dowell Constructors
- [x] VIC 6282015 - Ballast Regulator - Unregistered    (Currently in Red Flag in PG) - EXPIRE 02/2018
- [x] VIC 6292015 - Tamper - Unregistered    (Currently in Red Flag in PG) - EXPIRE 03/2018

Howell Rail
- [x] VIC 8352014 - Excavator - ZKO-528     (ACTUALLY THATS IN GREEN FLAG ALREADY) - EXPIRE 02/2019

Jordan Rail
- [x] VIC 7412015 - Dumper - 1HB-6XK    (Currently in Assessment in PG) - EXPIRE 12/2019
- [x] VIC 7372013 - Dumper - 25485-1   (Currently in Red Flag in PG) - EXPIRE 02/2019

Montgomery Constructions & Rail
- [x] VIC 7822013 - Utility - QYR-437   (Currently in Assessment in PG) - EXPIRE 03/2018
- [x] VIC 7832013 - Utility - RHJ-801   (Currently in Assessment in PG) - EXPIRE 03/2018

Rail Maintenance Services
- [x] VIC 2762013 - Utility - ZHG-285   (Currently in Assessment in PG) - EXPIRE 02/2018
- [x] VIC 2882013 - Sleeper Trolley - Unregistered  (Currently in Red Flag in PG) - EXPIRE 03/2018
- [x] VIC 7032013 - Truck - 1HX-9PJ - (CAN YOU GUYS SEE THIS PLANT IN PLANTGUARD???) - EXPIRE 02/2018

Thanks Gents

**Comment by markstreaka** [comment]
Out of 10 plant in this issue only 3 had a satisfactory result with changing. Closing cases doesn't change flag status. Some plant not even in PlantGUARD. It is a pity it has taken 12 days to find this out. @jpike88 and @alexkingma1 please do not ignore GitHUB issues created by @LachiePenn. These ones to change flag status of plant are extremely important. See issues below:

VIC 6282015 - NO row in assessment table so cannot update expiry
VIC 6292015 - NO row in assessment table so cannot update expiry
VIC 7372013 - Still RED FLAGGED after Case closed and expiry changed
VIC 7822013 - NOT in plant table
VIC 7832013 - NOT in plant table
VIC 2882013 - Still RED FLAGGED after Case closed and expiry changed
VIC 7032013 - NOT in plant table

**Comment by jpike88** [comment]
@LachiePenn VIC 7032013 does not exist in PlantGUARD
